### ISSUE TITLE
Bug: Issue with auto-recruiter resetting unit counts.

### ISSUE THREAD

**Issue by Norrec508** [uaktags/OpenThrone#20]
I've been training workers and army but they keep getting reset to much lower numbers

**Comment by uaktags** [comment]
Can you provide a walkthrough of what you're doing and seeing, as I'm not sure I'm tracking what you mean.

**Comment by Norrec508** [comment]
I've been training workers and army it eventually puts some of them back to being citizens.

**Comment by uaktags** [comment]
Okay, so you currently have 32Citizens and 30 Workers.
[
  {
    "type": "CITIZEN",
    "level": 1,
    "quantity": 32
  },
  {
    "type": "WORKER",
    "level": 1,
    "quantity": 30
  },
  {
    "type": "OFFENSE",
    "level": 1,
    "quantity": 0
  },
  {
    "type": "DEFENSE",
    "level": 1,
    "quantity": 0
  },
  {
    "type": "SPY",
    "level": 1,
    "quantity": 0
  },
  {
    "type": "SENTRY",
    "level": 1,
    "quantity": 0
  }
]

What are the values you're entering and buttons you're clicking, and then things you're seeing?

If you type 20 into the Soldier's field, and click train, your Citizens in the left and heading should reduce by 20 and your Soldiers should increase from 0 to 20. No?
If you don't do anything else and wait (you said..."eventually") what happens?

**Comment by Norrec508** [comment]
They would turn into soldiers but hen revert back to citizens. My worker count is at 14 right now. I keep training them but my count will not stay up

**Comment by uaktags** [comment]
Not a very helpful recreation of steps to show an issue -_-. Please try to be more descriptive. 

Here's a video that shows the issue.

https://github.com/uaktags/DarkCurse-nextjs/assets/893684/7ed448bb-0890-464b-a3e4-90bb6b9c02f6

**Comment by Norrec508** [comment]
It seems to happen when I recruit. I just used the auto recruit and 42 of my workers and troops were put back to citizens

**Comment by NunosDC** [comment]
I was able to run the auto recruiter and my numbers too are way off I went from 700 citizens to 494 and 46 citizens when I would expect 25. 
![image](https://github.com/uaktags/DarkCurse-nextjs/assets/146961378/71a75e53-bf32-4bde-9628-95e4f87b1248)

and it seemed to move advanced type 2 units back to type 1 units at the same time.

![image](https://github.com/uaktags/DarkCurse-nextjs/assets/146961378/03770a42-f384-4a8f-a894-0bb4a18921d6)

**Comment by uaktags** [comment]
Are you guys "losing" workers and army" guys to a random number or are you guys going back to a previous amount you had before you started auto-clicker?

The only code I found that could lead to a discrepency is during auto-recruit when your own link pops back up. At that point, we were incorrectly grabbing your server session which doesn't necessarily have the latest information, and incrementing the Citizens on that. So if the server session is of a previous state that wasn't nullified and updated, then you'll essentially be reset back to that previous session's counts.

**Comment by Norrec508** [comment]
I always ended up with 42 citizens after i used auto recruiter. I would lose workers and army
