### ISSUE TITLE
Number seperators 

### ISSUE THREAD

**Issue by NunosDC** [uaktags/OpenThrone#37]
I remember in Gold at least in the Settings section being able to choose between a comma or a dot and now that some stats are getting larger I notice we need those on some pages that they are not available currently.

![image](https://github.com/uaktags/DarkCurse-nextjs/assets/146961378/130133ca-0bf7-4fb3-b70f-319989443242)

![image](https://github.com/uaktags/DarkCurse-nextjs/assets/146961378/d57240e7-284f-4c16-92ab-bdfc5d26ec9f)

![image](https://github.com/uaktags/DarkCurse-nextjs/assets/146961378/d390aae4-ae29-4a63-a038-623f60d9784a)

May be some others and I think this ties in with your other issue about client or server side number seperators. ;)

**Comment by uaktags** [comment]
Yea, i need to implement a player settings so you can set the format yourself, and then we just do everything on the client side without any ill-effects
