### ISSUE TITLE
No Armory (Current Upgrade)

### ISSUE THREAD

**Issue by BronzeMantis** [uaktags/OpenThrone#39]
I have unlocked Dagger  +25 OFFENSE Which I presume is Leather Armory 1 because Hatchet is Leather Armory 2 and that's the next.
But it say's my current upgrade is No Armory
![AU](https://github.com/uaktags/DarkCurse-nextjs/assets/150398391/066892c1-70dd-4858-bc50-6e92de140650)

**Comment by uaktags** [comment]
Daggers are Level 1 items, so they'd be part of the "No Armory". Hatchets require a Leather Armory 1 item. Need to check their bindings in constants to make sure that's accurate. It's looking like things may be off by 1 Armory Level
